### ISSUE TITLE
主题

### ISSUE THREAD

**Issue by alvincheang** [ilay1678/dujiaoka-mod#15]
请问从1.8.3升去魔改版是不是只能使用choice和amazeui主题？
luna和hyper都不能使用吗？
env编辑了就会显示500错码

**Comment by iLayPark** [comment]
魔改版没有加以上两款主题

**Comment by alvincheang** [comment]
哦好的清楚了 比较喜欢新款主题，但需要用到魔改版功能，我乖乖用amazeui呗，谢谢你~
