### ISSUE TITLE
V免签--2人+都下单一个商品，不知道哪边支付的。

### ISSUE THREAD

**Issue by jiuyueidc** [iLay1678/dujiaoka-mod#2]
比如商品1元，A用户下单还没支付的情况下，又有B用户下单同一商品也是1元。
那么支付后网站不知道谁支付的

测试发现：A用户下单支付成功，网站会显示B下单用户成功支付的消息（B未支付）

**Comment by iLay1678** [comment]
V免签如果已经有一个1元的未支付订单，第二个1元的订单支付金额必须是1.01或其他，具体看你的V免签设置，因为V免签就是根据支付金额来区分订单的

**Comment by jiuyueidc** [comment]
那岂不是不能并发下单，

**Comment by iLay1678** [comment]
可以并发，付款时一定要严格按照付款页面提示的付款金额付款，而不是订单金额。如B用户付款时付款界面可能会提示付款1.01元，那么B用户必须付款1.01元

**Comment by jiuyueidc** [comment]
我测试，付款页面和商品价格一样，v免签没有做到`递增递减 多1分少1分` 支付后系统不能准确判断谁付款的。

**Comment by iLay1678** [comment]
![image](https://user-images.githubusercontent.com/7021399/94215568-9a819f80-ff0f-11ea-8de5-f51cab9a7477.png)
正常情况下会有这个提示，我这边只是对接V免签，V免签问题请去V免签项目提issue

**Comment by jiuyueidc** [comment]
我又测试了下，正常，金额有变化，奇怪。
对了 魔改发卡订单超时时间推荐设置几分钟，还有免签推荐时间。

**Comment by iLay1678** [comment]
这个根据业务来吧，一般5分钟就行
