### ISSUE TITLE
请问一下首页弹窗

### ISSUE THREAD

**Issue by chunlee8189** [iLay1678/dujiaoka-mod#4]
[![DZhon0.png](https://s3.ax1x.com/2020/11/17/DZhon0.png)](https://imgchr.com/i/DZhon0)

请问如何关闭首页弹窗 或是 编辑弹窗内容？

**Comment by iLay1678** [comment]
清除缓存，或者更换浏览器

**Comment by chunlee8189** [comment]
感谢即时反馈，尝试了一下，成功！
